### ISSUE TITLE
Behavior, Tag and Property

### ISSUE THREAD

**Issue by marty-macfly** [mhndev/yii2-taxonomy-term#1]
Hi guy,

First for this module it was part of what i was looking for :) I made some work around this modul to make it suits my need so perhaps you want to have a look, it's here https://github.com/Marty-Macfly/yii2-taxonomy/

I was looking for a taxonomy module to add taxonomy to any model of my app and i do not what to have many tables for every model, so your module was perfect for that need. Thanks for that.

I was not really found of the usage of trait to extend a model, so i've implemented behavior (i think they do quite the same has you trait).

Also i've extend some of your model to add some small features. I think the most interesting one is on the Term model to add the increase and decrease of usage counter in it (instead of in the trait).

If you want i can make pull request just let me know if your are interested by some of them. And thanks again for your work.

Cheers,
Macfly

**Comment by mhndev** [comment]
Hi,
first of all thanks for your attention to this package,
and absolutely I'm interested and I would be happy if you can contribute on
this repository.

thanks,
Majid Abdolhosseini
